isolated-vm.d.ts
I named them `ExternalCopyCopyOptions` since they're options during copy.
=> Update typescript definitions with "ignored" versions and external copy options

isolated-vm.d.ts, src/reference_handle.cc
- Adds the NativeModule type
- Adds Transferable, a union type representing all transferable types
- Adds Copy<T>, a value that's been copied into another isolate
- Made arguments to `apply` functions optional
If I'm missing any Transferable types, I'd love to add them. Makes our logic a bit more robust :)
=> Updated and corrected typescript definitions

isolated-vm.d.ts
`Module#instantiateSync` had no return type specified in the typings. I assume it mirrors the signature of `Module#instantiate` except without the Promise.
=> fix: typings

README.md
fixes g++ 4.8 error: unrecognized command line option ‘-std=c++14’
=> amazon linux ami c++14 support in gcc

README.md
We've been using `isolated-vm` at Algolia for our crawler (which I've been a dev on for the entire project life) for the past year and I have to say that it was a blast. It's one of our core security mechanisms.
We spent so much time looking at alternatives, that when we discovered it, it almost felt too good to be true.
By the way, `How to run untrusted JavaScript code` is a banned question on StackOverflow because it has been asked so many times. I've mentioned `isolated-vm` in one of the most popular ones and flagged a lot of them as duplicates.
https://stackoverflow.com/questions/10937870/how-to-run-untrusted-code-serverside
I plan to do a few presentations about our usage of the lib, and would be happy to see our name in your user list. :)
=> Add Algolia to the list of users

isolated-vm.d.ts
Very simple change to allow for code such as the following when using TypeScript:
```ts
import ivm from "isolated-vm";
const isolate = new ivm.Isolate();
const context = isolate.createContextSync();
// Previously saw the following error at this line:
// Argument of type 'typeof import("isolated-vm")' is not assignable to parameter of type 'Transferable'.
context.global.setSync("_ivm", ivm);
// ...
```
=> Declare isolated-vm module as transferable in TypeScript types

src/external_copy/external_copy.cc, tests/exception-info.js
We've stumbled upon a segfault that occurs when an ivm isolate throws an Error which has a non-string message property value.
This patch is enough to stop the crash by simply using the stringified version of the value if it's not already a string, and defaults to a worst-case scenario of an empty string.
Minimal repro:
```ts
const ivm = require("./isolated-vm");
(async () => {
const isolate = new ivm.Isolate();
const ctx = await isolate.createContext();
await ctx.eval(`
const err = new Error;
err.message = 1; // any non-string primitive value
throw err;
`);
})();
```
Backtrace:
```
Thread 1 "node" received signal SIGSEGV, Segmentation fault.
ivm::ExternalCopyString::CopyInto (this=this@entry=0x7fffe0001968) at ../src/external_copy/string.cc:102
102             if (value->size() < 1024) { …
```
=> Fix segfault when throwing Errors with non-string primitive messages

isolated-vm.d.ts
This simply seemed to be omitted.  See the docs:
https://github.com/laverdet/isolated-vm/tree/56cc60b3486536ac3f90613fd0ec5fa58ef2c193#contextevalcode-options-promise
=> Add ScriptOrigin to ContextEvalOptions types

README.md, binding.gyp, isolated-vm.d.ts, src/isolate/strings.h, src/module/cpu_profiler_handle.cc, src/module/cpu_profiler_handle.h, src/module/isolate_handle.cc, src/module/isolate_handle.h, tests/cpu-profiler.js
Hi @laverdet ,
Thanks again for the fantastic library.
It seems like profiling can only be done via connecting to `inspector` with debug mode. So I am adding a
new method into the isolate to create a one-time CPU profiler.
The CPU profiler will be disposed of once the `stopProfiling` is called.
I am very, very new to the c++ and v8 side of changes; feel free to point out what I need to change in the
PR. I will update them asap. 
Tested in:
* node 10
* node 12
* node 14
* node 16
* node 18
=> Add cpu profiler capability to isolate

tests/cpu-profiler.js
hi @laverdet ,
I found out that when the node process does not have enough samples, it discards the function name, which causes the CPU-profiler test to be flaky.
So I increased the loop count by double, seems like it never fails locally anymore after increasing the loop count(apple m1max locally). I will update the test if it continues to happen. I may remove the function name check in the future if it keeps happening.
=> Increase loop time to make sure node16 function name shows

.github/workflows/prebuild.yml
this allows to use the prebuilt images on systems that do not have glibc v3 installed, e.g. the official selenium and cypress docker images
=> prebuild on ubuntu 20.04

src/module/isolate.cc, tests/worker-reload.js
Loading the module in one worker, closing that worker again, and then trying to load the module in a second worker fails with `Error: Module did not self-register`. From what I can tell, the core issue is this one: https://github.com/nodejs/node/issues/48353.
This should fix the issue, which was also mentioned in this comment: https://github.com/laverdet/isolated-vm/issues/138#issuecomment-1077856679. I'm however not too familiar with native Node.js addon development, so I'm unsure if this has any unintended side effects (it really shouldn't, though).
Node.js unloads unreferenced native addons if not on the main thread[^1], but the shared object doesn't necessarily get fully unloaded from calling `dlclose()` (at least on Linux, due to... reasons?), which means it won't self-register when …
=> Improve support for reloading module in multiple workers

package.json
This change let node-gyp choose the number of jobs to build during initial installation. This avoids threshing smaller machines with low RAM/CPUs.
=> Scale node-gyp automatically

src/module/context_handle.cc
CompileFunctionInContext was removed.
See https://github.com/nodejs/node-v8/issues/214.
Fixes #436.
=> Fix running on Node 20.11

src/isolate/allocator_nortti.cc, src/isolate/environment.cc
* Remove pointless #define _GNU_SOURCE. It is already defined by gyp, and defining it after all the includes does nothing anyway.
* unary minus operator applied to unsigned type, result still unsigned
=> Fix compiler warnings

src/external_copy/external_copy.cc, src/external_copy/external_copy.h
It seems the support for copying `Big{Int64,Uint64}Array`s added with 2d06cc30ba5200e8a8d70e7b5022b5750902b1ce is incomplete. Presently, the following results in a crash:
```js
import ivm from 'isolated-vm';
const isolate = new ivm.Isolate();
const context = await isolate.createContext();
const array = await context.eval('new BigUint64Array(12345)', { copy: true }); // crashes
console.log(array);
```
The crash is caused by the `NewTypedArrayView` function called by `ExternalCopyArrayBufferView::CopyInto`. It does not cover the `Big{Int64,Uint64}Array` types and instead throws a `std::exception` which is not handled anywhere. This is likely an oversight, and this PR fixes it.
https://github.com/laverdet/isolated-vm/blob/be71d2512cd583ad3e51672ff9b6e1f9ef34b279/src/external_copy/external_cop …
=> Fix copying of BigInt64Array and BigUint64Array

.github/workflows/prebuild.yml, package.json
This updates node-gyp dependency, and should fix the build on macos.
=> Update prebuild to v13

README.md
This removes unneeded packages from the list of RHEL requirements and adds make as it’s needed by node-gyp.
=> Update RHEL requirements in README.md

src/isolate/scheduler.cc, src/module/isolate_handle.cc
1/ `isolate_handle.cc`:
`snapshot.data`, which is allocated by V8 as `new char[]`  ([snapshot.cc:546](https://github.com/nodejs/node/blob/d545984a02eb84ad030511d7eb7968bc1e4909be/deps/v8/src/snapshot/snapshot.cc#L546)) is owned by `snapshot_data_ptr`, which is of type `unique_ptr<const char>` => `delete` is called upon destruction, `delete[]` should be called instead
=> changed the type of the unique_ptr to reflect this
---
2/ `scheduler.cc`:
`uv_async` is allocated as `uv_async_t` (128 B) but deleted as `uv_handle_t` (96 B)
=> added a cast back from `uv_handle_t*` to `uv_async_t*` before deleting
---
Technically, these situations are UB, but practically they don't cause any issues. They came up as a result of running the test suite with ASan which doesn't complain anymore after this …
=> fix incorrect types of pointers

.github/workflows/prebuild.yml
Use gcc 11 as default gcc version to support more distributions, as gcc 12 is not shipped with most distros by default.
=> Update prebuild.yml to use gcc 11
